version: '3'

services:
  ############################
  #   docker image updates   #
  ############################ 
  renovate:
    build: https://github.com/dome4/renovate-cron.git#main
    restart: always
    environment:
      - RENOVATE_GIT_AUTHOR=Renovate Bot <bot@${DOMAINNAME}>
      - RENOVATE_USERNAME=${RENOVATE_USERNAME}
      - RENOVATE_TOKEN=${RENOVATE_TOKEN}
      - RENOVATE_PLATFORM=gitea
      - RENOVATE_ENDPOINT=https://${DOMAINNAME}/api/v1
      - GITHUB_COM_TOKEN=${RENOVATE_GITHUB_TOKEN}
      - LOG_LEVEL=debug
      - RENOVATE_AUTODISCOVER=true
      # - SCHEDULE=*/30 * * * * * # debug - every 30 seconds
      - SCHEDULE=0 5 * * * # every day at 5 am
      - TIME_ZONE=Europe/Berlin 
    networks:
      - renovate

networks:
  renovate: